# required environment
language: scala
scala:
  - "2.11.8"

jdk:
  - oraclejdk8

node_js:
  - "4.2.2"

# build only master branch (we specify PR build in Travis)
branches:
  only:
    - master

# build script
script:
  - npm install
  - sbt compile test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

# reusing sbt cache in container based infrastructure on travis
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
